### ISSUE TITLE
Use user-defined input type instead of String

### ISSUE THREAD

**Issue by AlisCode** [PradeepKumarRajamanickam/kurinji#39]
Hey there, 

Looks like this crate is already fairly usable! good work :) 

I was wondering why the "logical input type", is a `String`. I could potentially write code that binds a gamepad button to a wrong name, and ship my app as-is (with an error), while there could be another solution that would statically prevent that kind of problem. 

I think users should be able to define their own Input type, e.g. : 

```rust
enum GameInput {
    MoveRight,
    MoveLeft,
    Jump,
    Shoot,
}
```

Then Kurinji **should be generic over that value**, instead of forcing the user to use a String. You could set the default value of the generic to String if you want, but user could optionaly use their own type. The big advantage you gain from this is type-safety on your inputs : it would then be impossible to mistakenly type "JUMPE" instead of "JUMP", such error is now caught by the compiler. Yes, to solve that problem you could also use constants, but : 
* It's more idiomatic to use an enum here because you know beforehand the type of input that users are going to be able to do. If you dont, then you can always resort to using a String, but you're not limited to it.   
* You can also **safely** store information about an input, such as in my example having a `Jump(Player)` variant, or `Shoot(ProjectileType)`. 

Deserializing your input also works, because Serde is great. Of course, you get a runtime error if you failed to write your input name correctly, but there's nothing we can do about that.     

Another cool thing is you potentially, get a performance boost if hashing that GameInput type is cheaper than hashing a String. And it is my understanding that using e.g. `FnvHashMap` to hash in that case would be a performance boost indeed - not that this operation is extremely intensive anyway...  

I suggest to replace the definition of Kurinji with `pub struct Kurinji<InputType = String>` and let the compiler guide one through the refactor.  

Using the strongly-typed variant could then be as simple for a user as defining `pub type Kurinji = kurinji::Kurinji<GameInput>;` and use that type alias everywhere in the codebase.

**Comment by PradeepKumarRajamanickam** [comment]
Hey, This question has already been answered.
https://github.com/PradeepKumarRajamanickam/kurinji/issues/34#issuecomment-731177287

I think using constants is ideal, because it is simple and it gets the job done. I tend to avoid complexity where I can i.e. as long as it does not affect feature set I want to give. My general approach is keeping things simple, data-driven (when possible) and focus more on ease of use. For me my work being useful to people in some meaningful way is the driving factor following strict idiomatic conventions is kind of low on my personal priority list...:)

With regards to performance, for the general use case the data won't be that heavy so the gain will be too small to notice. I don't think it is worth the effort.

Closing ticket
